export const CONFIGS = {
    benefit: {
        max: 6,
        layout: [2, "full"],
        fields: [
            {
                key: "icon",
                type: "icon",
                label: "Lucide Icon",
                placeholder: "e.g. zap",
                iconType: "lucide",
                previewDefault: "zap",
            },
            { key: "title", type: "text", label: "Title", placeholder: "" },
            { key: "desc", type: "textarea", label: "Description", rows: 2 },
        ],
    },

    industries: {
        max: null,
        layout: [2, "full"],
        fields: [
            {
                key: "icon",
                type: "icon",
                label: "Lucide Icon",
                placeholder: "e.g. building",
                iconType: "lucide",
                previewDefault: "building",
            },
            {
                key: "title",
                type: "text",
                label: "Title",
                placeholder: "e.g. Healthcare",
            },
            { key: "desc", type: "textarea", label: "Description", rows: 2 },
        ],
    },

    casestudy: {
        max: 6,
        layout: ["full", 2, 2],
        fields: [
            { key: "featured", type: "checkbox", label: "Featured Card" },
            {
                key: "metric",
                type: "text",
                label: "Metric *",
                placeholder: "+320% / 4x / $180K",
            },
            {
                key: "title",
                type: "text",
                label: "Title *",
                placeholder: "Organic Traffic",
            },
            {
                key: "tag1",
                type: "text",
                label: "Tag 1",
                placeholder: "E-commerce",
            },
            { key: "tag2", type: "text", label: "Tag 2", placeholder: "SEO" },
        ],
    },

    faqs: {
        max: 4,
        arrayKey: "faqs",
        layout: [],
        fields: [
            { key: "question", type: "text", label: "Question *" },
            { key: "answer", type: "textarea", label: "Answer *", rows: 3 },
        ],
    },

    tech: {
        max: null,
        layout: [2],
        fields: [
            {
                key: "icon",
                type: "icon",
                label: "Devicon Class",
                placeholder: "e.g. devicon-laravel-plain",
                iconType: "devicon",
                previewDefault: "devicon-devicon-plain",
            },
            {
                key: "title",
                type: "text",
                label: "Title",
                placeholder: "e.g. Laravel Development",
            },
        ],
    },
    challenges: {
        max: 6,
        arrayKey: "items",
        layout: [],
        fields: [
            {
                key: "issue",
                type: "textarea",
                label: "Issue",
                rows: 4,
            },
            {
                key: "fixed",
                type: "textarea",
                label: "Fixed",
                rows: 5,
            },
            {
                key: "result",
                type: "text",
                label: "Result Line",
            },
        ],
    },
    process: {
        max: 4,
        arrayKey: "items",
        layout: [1],
        fields: [
            {
                key: "icon",
                type: "icon",
                label: "Icon",
                iconType: "lucide",
                previewDefault: "star",
            },
            {
                key: "step",
                type: "text",
                label: "Step Number (01, 02...)",
                placeholder: "autogenerated = 01, 02...",
            },
            {
                key: "title",
                type: "text",
                label: "Title",
            },
            {
                key: "desc",
                type: "textarea",
                label: "Description",
                rows: 3,
            },
        ],
    },
    stats: {
        max: 6,
        arrayKey: "items",
        layout: [],
        fields: [
            {
                key: "value",
                type: "text",
                label: "Value (e.g. 500+, $50M+, 4.9)",
            },
            {
                key: "label",
                type: "text",
                label: "Label (e.g. Clients Served)",
            },
        ],
    },
    roicalculator: {
        max: 10,
        arrayKey: "industries",
        layout: [2, "full"],
        fields: [
            {
                key: "label",
                type: "text",
                label: "Industry Label",
                placeholder: "e.g. E-commerce",
            },
            {
                key: "value",
                type: "text",
                label: "Value Key",
                placeholder: "e.g. ecommerce",
            },
            {
                key: "multiplier",
                type: "text",
                label: "Multiplier",
                placeholder: "e.g. 1.2",
            },
        ],
    },

    custom: {
        max: 8,
        arrayKey: "paragraphs",

        layout: ["full"],

        fields: [
            {
                key: "text",
                type: "textarea",
                label: "Paragraph",
                placeholder: "Enter paragraph...",
                rows: 5,
            },
        ],
    },

    comparison: {
        max: 10,
        arrayKey: "items",
        fields: [
            {
                key: "feature",
                type: "text",
                label: "Feature",
            },
            {
                key: "us_text",
                type: "textarea",
                label: "Your Value (BlueOrbit)",
                rows: 3,
            },
            {
                key: "agency_text",
                type: "textarea",
                label: "Typical Agency",
                rows: 3,
            },
            {
                key: "diy_text",
                type: "textarea",
                label: "DIY",
                rows: 3,
            },
        ],
    },

    testimonials: {
        max: 10,
        arrayKey: "items",
        fields: [
            {
                key: "rating",
                type: "number",
                label: "Rating (1-5)",
                min: 1,
                max: 5,
                step: 1,
            },
            {
                key: "text",
                type: "textarea",
                label: "Testimonial Text",
                rows: 4,
            },
            {
                key: "name",
                type: "text",
                label: "Client Name",
            },
            {
                key: "role",
                type: "text",
                label: "Role / Industry",
            },
            {
                key: "company",
                type: "text",
                label: "Company (optional)",
            },
            {
                key: "image",
                type: "text",
                label: "Image URL",
            },
        ],
    },

    trust: {
        max: 6,
        arrayKey: "features",
        fields: [
            {
                key: "icon",
                type: "text",
                label: "Icon (Lucide name)",
                iconType: "lucide",
                previewDefault: "zap",
            },
            { key: "title", type: "text", label: "Title" },
            { key: "desc", type: "textarea", label: "Description", rows: 3 },
        ],
    },

    trust_partners: {
        max: 10,
        arrayKey: "partners",
        fields: [
            {
                key: "icon",
                type: "text",
                label: "Devicon Class",
                iconType: "devicon",
                previewDefault: "devicon-devicon-plain",
            },
        ],
    },

    trust_tags: {
        max: 10,
        arrayKey: "tags",
        fields: [{ key: "value", type: "text", label: "Tag Text" }],
    },

    usecases: {
        max: 9,
        arrayKey: "items",
        layout: [],
        fields: [
            {
                key: "title",
                type: "text",
                label: "Industry Title",
                placeholder: "e.g. Healthcare",
            },
            {
                key: "link",
                type: "text",
                label: "Read More Link",
                placeholder: "/industries/healthcare",
            },
            {
                key: "points",
                type: "repeater",
                label: "Bullet Point",
                placeholder: "Enter bullet point...",
                max: 6,
            },
        ],
    },
};
